### ISSUE TITLE
Will issues from codehaus.org be migrated?

### ISSUE THREAD

**Issue by christoffers** [mojohaus/clirr-maven-plugin#1]
Hello,
we have been monitoring the issues 
http://jira.codehaus.org/browse/MCLIRR-64 and
http://jira.codehaus.org/browse/MCLIRR-65,
but we cannot find them here on GitHub.

Please tell me, if you are going to migrate the issues from jira.codehaus.org or if we should submit them again.

Thank you!

**Comment by khmarbaise** [comment]
If you could submit them an other time would be great… Thanks for the support.

**Comment by christoffers** [comment]
Ok, we will submit the issues again. Thank you for the quick response.
