### ISSUE TITLE
Please Release Version with official BCEL 6.0

### ISSUE THREAD

**Issue by hazendaz** [mojohaus/clirr-maven-plugin#19]
See PR #18.  While #3 claims this doesn't fully address java 8, it does fix use cases.  We just migrated mybatis 3 to use java 8 on unit tests only.  Site generation does work with either the findbugs solution or the official.  We however don't want to introduce snapshot plugins into our builds for obvious reasons.  It does not appear there are any real significant changes or show stoppers preventing 2.8 from being released.  Can we get an official cut soon?

**Comment by magro** [comment]
+1

**Comment by olamy** [comment]
done

**Comment by magro** [comment]
@olamy Is 2.8 already released? Can't find it, and the pom.xml still contains 2.8-SNAPSHOT. If it's not yet released I'd suggest to reopen this.

**Comment by olamy** [comment]
@magro why reopen it? I will only change the title 
BTW I will try to release next week depending on my spare time

**Comment by magro** [comment]
@olamy changing the title is fine :-) Looking forward to the release, very much appreciated!

**Comment by magro** [comment]
@olamy ping :-)

**Comment by olamy** [comment]
OMG I will for sure.
Sorry for delay :-(

**Comment by lbergelson** [comment]
@olamy @magro Is there a corresponding maven release?  I only see 2.7 in central still.

**Comment by magro** [comment]
@olamy Same here - where did you release it to?

**Comment by magro** [comment]
@olamy Ah, found it in the staging repo - https://oss.sonatype.org/service/local/repositories/orgcodehausmojo-1069/content/org/codehaus/mojo/clirr-maven-plugin/2.8/

Seems it's already closed, perhaps you missed to "Release"?

**Comment by olamy** [comment]
guys we have a vote process which takes 3 days.
So now it's fixed, deployed etc...
Cheers

**Comment by magro** [comment]
Makes sense, thanks for the update!
