### ISSUE TITLE
Add support for Java 8

### ISSUE THREAD

**Issue by AndrewJCarr** [mojohaus/clirr-maven-plugin#3]
I'm uplifting a project to Java 1.8 and the clirr-maven-plugin is dying on me in the reporting section with the error:

```
[INFO] org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18
```

Stack trace: [Gist](https://gist.github.com/AndrewJCarr/4a76d41bbebad7db46be)

It appears that the Apache BCEL dependency needs to be updated to version 6.0 when it gets released.

I also downloaded the BCEL 6.0 snapshot version in consideration for release, managed the dependency version, and it succeeded to generate the report.

**Comment by AndrewJCarr** [comment]
Note: After some further debugging, project-info-reports-plugin is pulling bcel in as a transitive dependency. Since clirr is declaring the dependency, it would override the project-info-reports-plugin.

**Comment by bokken** [comment]
Does anyone know bcel's release plan?

**Comment by AndrewJCarr** [comment]
From their mailing list: http://mail-archives.apache.org/mod_mbox/commons-dev/201507.mbox/%3C20150719220950.Horde._yMpE-t8WTgygtKF5weW7Q1%40secure46.inmotionhosting.com%3E

It looks like they're trying to get it shipped soon.

**Comment by LasneF** [comment]
any news from this as bcel has released its version https://github.com/apache/commons-bcel/releases

**Comment by user667** [comment]
Replacing the explicit
```xml
<dependency>
  <groupId>org.apache.bcel</groupId>
  <artifactId>bcel</artifactId>
  <version>5.2</version>
</dependency>
```
with 
```xml
<dependency>
    <groupId>com.google.code.findbugs</groupId>
    <artifactId>bcel-findbugs</artifactId>
    <version>6.0</version>
</dependency>
```
did the trick for me. I wasn't able to find a non-RC version of above apache commons-bcel.

Any chance that Java8 compat. will make it into 2.8?

**Comment by klopfdreh** [comment]
May I ask if this is fixed with release 2.7? Apache Wicket (https://github.com/apache/wicket) uses clirr-maven-plugin and 8.0.0-M1 is going to be released, soon. It would be nice if we can update the plugin to get compatibility for Java 8, because this is also a requirement for Wicket 8. 👍

**Comment by vmassol** [comment]
Hi @klopfdreh On the XWiki project (http://xwiki.org) we've switched to using revapi, see http://massol.myxwiki.org/xwiki/bin/view/Blog/ByeByeCLIRRWelcomeRevapi

**Comment by klopfdreh** [comment]
Hi @vmassol - thanks a lot for that hint - we are going to have a look at it.

**Comment by Mahoney** [comment]
While this is in progress, is there any way to force v2.7 of the plugin to use com.google.code.findbugs:bcel-findbugs:6.0 rather than org.apache.bcel:bcel:5.2? I can include an extra dependency on the google version, but there's no <exclusions> tag within <plugin> in the Maven model to allow me to exclude the apache one.

**Comment by NegatioN** [comment]
+1 to Mahoney's question.
Also, are there any estimates for when 2.8 is releasing?

**Comment by vmassol** [comment]
Note that even though this issue is closed it doesn't add support for Java as the issue title claims ;) It just makes it not fail if you're under java 8 but use java 7 constructs.
